//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemDaiHoc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOANGHIEP\\DEV;Initial Catalog=QuanLyDiemTruongDaiHoc;Persist Security" +
            " Info=True;User ID=sa;Password=hoanghiep;TrustServerCertificate=True")]
        public string QuanLyDiemTruongDaiHocConnectionString {
            get {
                return ((string)(this["QuanLyDiemTruongDaiHocConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOANGHIEP\\DEV;Initial Catalog=QuanLyDiemTruongDaiHoc;Persist Security" +
            " Info=True;User ID=sa;Password=hoanghiep;Encrypt=True;TrustServerCertificate=Tru" +
            "e")]
        public string QuanLyDiemTruongDaiHocConnectionString1 {
            get {
                return ((string)(this["QuanLyDiemTruongDaiHocConnectionString1"]));
            }
        }
    }
}
